#!/bin/zsh

###############################################################################
# aliases
###############################################################################

# List all files colorized in long format, including dot files
alias la="ls -laF"

# get local IP addresses
alias localip="ipconfig getifaddr en0"

# Kill all the tabs in Chrome to free up memory
# [C] explained: http://www.commandlinefu.com/commands/view/402/exclude-grep-from-your-grepped-output-of-ps-alias-included-in-description
alias chromekill="ps ux | grep '[C]hrome Helper --type=renderer' | grep -v extension-process | tr -s ' ' | cut -d ' ' -f2 | xargs kill"
